CREATE TABLE CUSTOMER(
    ID INT NOT NULL,
    USERNAME VARCHAR(20),
    FIRSTNAME VARCHAR(20),
    SURNAME VARCHAR(20),
    SHIPPING_ADDRESS VARCHAR(20),
    EMAIL_ADDRESS VARCHAR(20), 
    PRIMARY KEY(ID)
);
CREATE TABLE PRODUCT (
    ID INT NOT NULL,
    NAME VARCHAR(20),
    DESCRIPTION VARCHAR(20),
    CATEGORY VARCHAR(20),
    LIST_PRICE NUMERIC(10, 2),
    QUANTITY_IN_STOCK NUMERIC(10, 2), 
    PRIMARY KEY(ID)
);