CREATE TABLE CUSTOMER(
    ID INT NOT NULL,
    USERNAME VARCHAR(20),
    FIRSTNAME VARCHAR(20) 
    SURNAME VARCHAR(20),
    SHIPPINGADDRESS VARCHAR(20),
    EMAILADDRESS VARCHAR(20), 
    PRIMARY KEY(ID)
)

CREATE TABLE PRODUCT (
    ID INT NOT NULL,
    NAME VARCHAR(20),
    DESCRIPTION VARCHAR(20),
    CATEGORY VARCHAR(20)
    LISTPRICE NUMERIC(10, 2),
    QUANTITYINSTOCK NUMERIC(10, 2), 
    PRIMARY KEY(ID)
)