CREATE TABLE CUSTOMER(
    Customer_ID INTEGER AUTO_INCREMENT (1000),
    USERNAME VARCHAR(20) NOT NULL,
    FIRSTNAME VARCHAR(20),
    SURNAME VARCHAR(20),
    PASSWORD VARCHAR(20) NOT NULL,
    SHIPPING_ADDRESS VARCHAR(20),
    EMAIL_ADDRESS VARCHAR(20), 
    PRIMARY KEY(USERNAME)
);

CREATE TABLE PRODUCT (
    PRODUCT_ID INT NOT NULL,
    NAME VARCHAR(20),
    DESCRIPTION VARCHAR(20),
    CATEGORY VARCHAR(20),
    LIST_PRICE NUMERIC(10, 2),
    QUANTITY_IN_STOCK NUMERIC(10, 2), 
    PRIMARY KEY(PRODUCT_ID)
);